drop package HABR_TRADEMODELLING_P;

drop function HABR_MARKETINDEXES_EMASIMPLE_F_CALC;
drop function HABR_MARKETINDEXES_EMASIMPLE_F_RECU;
drop function HABR_MARKETINDEXES_EMASIMPLE_F_AGRF;
drop function HABR_MARKETINDEXES_EMASIMPLE_F_MODE;

drop function HABR_MARKETINDEXES_CROSSES_F_CALC;


drop function HABR_MARKETINDEXES_OBV_F_CALC;
drop function HABR_MARKETINDEXES_OBV_F_SIMP;
drop function HABR_MARKETINDEXES_OBV_F_MODE;

drop function HABR_MARKETINDEXES_KELTNER_F_MODE;
drop function HABR_MARKETINDEXES_KELTNER_F_CALC;
drop function HABR_MARKETINDEXES_KELTNER_F_SIMP;

drop function HABR_MARKETINDEXES_PVT_F_CALC;
drop function HABR_MARKETINDEXES_PVT_F_MODE;
drop function HABR_MARKETINDEXES_PVT_F_SIMP;

drop function HABR_MARKETINDEXES_EMV_F_CALC;
drop function HABR_MARKETINDEXES_EMV_F_SIMP;


drop function HABR_MARKETINDEXES_CCI_F_CALC;
drop function HABR_MARKETINDEXES_CCI_F_SIMP;

drop function EMA; 
drop function WMA;


drop type HABR_MARKETINDEXES_RESULT_LIST_T;
drop type HABR_MARKETINDEXES_RESULT_T;

drop type EMA_IMPL_T;
drop type WMA_IMPL_T;

drop type EMA_DATA_T;
drop type WMA_ARRAY_T;
drop type WMA_DATA_T;

drop view LOAD_YAHOO_V;
drop table LOAD_YAHOO purge;
drop table HABR_MARKETINDEXES_PARMSEL_RESULTS purge;